# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog
from PyQt5.uic import loadUi
from PyQt5 import QtCore, QtGui, QtWidgets
from figure import *
from poem import poems
from decoding import *
from main import file_settings

reference_name = ''
fname = ' '

message = ''


class Ui_Coding(object):
    def setupUi(self, Coding):
        Coding.setObjectName("Coding")
        Coding.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Coding)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(750, 0, 40, 50))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("hello_html_65f450f.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(-30, 20, 801, 491))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("bg2.png"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(460, 310, 301, 201))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("mashinka.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.save_file = QtWidgets.QPushButton(self.tab_2)
        self.save_file.setGeometry(QtCore.QRect(40, 430, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.save_file.setFont(font)
        self.save_file.setStyleSheet("background-color: rgb(239, 41, 41);\n"
                                     "color: rgb(255, 255, 255);")
        self.save_file.setObjectName("save_file")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(490, 160, 241, 181))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("list1.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 800, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(52, 101, 164);\n"
                                    "color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.decode = QtWidgets.QPushButton(self.tab_2)
        self.decode.setGeometry(QtCore.QRect(40, 350, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.decode.setFont(font)
        self.decode.setStyleSheet("color: rgb(255, 255, 255);\n"
                                  "background-color: rgb(52, 101, 164);")
        self.decode.setObjectName("decode")
        self.browse = QtWidgets.QPushButton(self.tab_2)
        self.browse.setGeometry(QtCore.QRect(40, 260, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.browse.setFont(font)
        self.browse.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                  "color: rgb(0, 0, 0)")
        self.browse.setObjectName("browse")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("bgg.jpg"))
        self.label_12.setObjectName("label_12")
        self.message = QtWidgets.QTextBrowser(self.tab_2)
        self.message.setGeometry(QtCore.QRect(510, 180, 201, 141))
        font = QtGui.QFont()
        font.setFamily("Truetypewriter PolyglOTT")
        font.setPointSize(18)
        self.message.setFont(font)
        self.message.setStyleSheet("background-color: rgba(191, 64, 64, 0);")
        self.message.setObjectName("message")
        self.label_12.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.save_file.raise_()
        self.decode.raise_()
        self.browse.raise_()
        self.message.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(52, 101, 164);\n"
                                 "color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(750, 0, 40, 50))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("hello_html_65f450f.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(0, 50, 801, 491))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("bg.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(460, 310, 301, 201))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("mashinka.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(510, 180, 201, 171))
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Truetypewriter PolyglOTT")
        font.setPointSize(19)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setMouseTracking(False)
        self.plainTextEdit.setStyleSheet("background-color: rgba(191, 64, 64, 0);")
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit.setLineWidth(0)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(490, 160, 241, 181))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("list1.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.code = QtWidgets.QPushButton(self.widget)
        self.code.setGeometry(QtCore.QRect(40, 430, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.code.setFont(font)
        self.code.setStyleSheet("background-color: rgb(239, 41, 41);\n"
                                "color: rgb(255, 255, 255);")
        self.code.setObjectName("code")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("bgg.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.plainTextEdit.raise_()
        self.label_6.raise_()
        self.code.raise_()
        self.tabWidget.addTab(self.widget, "")
        Coding.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Coding)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Coding.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Coding)
        self.statusbar.setObjectName("statusbar")
        Coding.setStatusBar(self.statusbar)

        self.retranslateUi(Coding)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Coding)

        self.browse.clicked.connect(self.browsefiles)
        self.message.setText('Сообщение')
        self.code.clicked.connect(self.message_getting)
        self.decode.clicked.connect(decode)
        self.save_file.clicked.connect(self.opening_file)

    def retranslateUi(self, Coding):
        _translate = QtCore.QCoreApplication.translate
        Coding.setWindowTitle(_translate("Coding", "MainWindow"))
        self.save_file.setText(_translate("Coding", "СОХРАНИТЬ СООБЩЕНИЕ"))
        self.label_11.setText(_translate("Coding", "          КРОНШТАДТСКИЙ МОРСКОЙ КАДЕТСКИЙ ВОЕННЫЙ КОРПУС"))
        self.decode.setText(_translate("Coding", "РАСШИФРОВАТЬ"))
        self.browse.setText(_translate("Coding", "ВЫБРАТЬ ФАЙЛ"))
        self.message.setHtml(_translate("Coding",
                                        "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'Truetypewriter PolyglOTT\'; font-size:5pt; font-weight:400; font-style:normal;\">\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Здесь появится сообщение</p>\n"
                                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Coding", "Дешифратор"))
        self.label.setText(_translate("Coding", "          КРОНШТАДТСКИЙ МОРСКОЙ КАДЕТСКИЙ ВОЕННЫЙ КОРПУС"))
        self.plainTextEdit.setPlainText(_translate("Coding", "Введите сообщение здесь..."))
        self.code.setText(_translate("Coding", "ЗАШИФРОВАТЬ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Coding", "Шифратор"))

    def message_getting(self):
        # os.remove('result.txt')
        # file_settings()
        self.mes = self.plainTextEdit.toPlainText()
        print(self.mes)
        with open('message.txt', 'w', encoding='utf-8') as self.m:
            self.m.write(self.mes)
        poems()
        # coding()

        new_method()

        figure()

    def browsefiles(self):
        global fname
        global reference_name
        reference_name = ''
        fname = ' '
        fname = QFileDialog.getOpenFileName(None, 'Open', '')
        print(fname)

        i = -1
        current = fname[0][i]
        while current != '/':
            reference_name += current
            i -= 1
            current = fname[0][i]

        reference_name = ''.join(reversed(reference_name))
        # print(reference_name)

        self.browse.setText(reference_name)
        # print(decoding.get_message(reference_name))
        self.message.setText(get_message(reference_name))

    def opening_file(self):
        '''output_mes = ''
        with open('uncoded.txt', 'r') as message:
            for i in message:
                print(i)
                for j in i:
                    print(j)
                    if j != '!':
                        output_mes += j
                    else:
                        break'''
        with open('message.txt', 'r', encoding='utf-8') as mes_file:
            output_mes = mes_file.read()
            self.message.setText(output_mes.upper())


import main_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Coding = QtWidgets.QMainWindow()
    ui = Ui_Coding()
    ui.setupUi(Coding)
    print(fname, reference_name)
    Coding.show()
    sys.exit(app.exec_())
